name: ferenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - easydict 
  - numpy
  - pandas
  - pillow
  - pip
  - protobuf
  - python
  - pytorch
  - scikit-image
  - scikit-learn
  - scipy
  - tensorboard
  - tensorboardx
  - tensorflow
  - torchvision
  - tqdm
